apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: web-server
        image: ghcr.io/YOUR_GITHUB_USERNAME/demo-app:latest # This will be replaced by the pipeline
        ports:
        - containerPort: 8080
          envFrom: # Load all keys from the ConfigMap as environment variables [cite: 88, 210]
          - configMapRef:
              name: demo-config
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort